version: '3.8'
services:
  fastapi:
    build:
      context: .
    ports:
      - 8000:8000
    command: uvicorn main:app --reload --port 8000 --host 0.0.0.0
  telegram_bot:
    build: .
    ports:
      - 8080:80